services:
    alg.ForumSponsor.listener:
        class: alg\ForumSponsor\event\listener
        arguments:
            - @template
            - @user
            - @request
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
