services:
    alg.forumsponsor.listener:
        class: alg\forumsponsor\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@request'
        tags:
            - { name: event.listener }
