services:
    alg.ForumSponsor.listener:
        class: alg\ForumSponsor\event\listener
        arguments:
            - @template
            - @user
        tags:
            - { name: event.listener }
